#!/bin/bash
# Written by Haiyun Jin 2014/07/08
# This script is for calculating block average from ??
#

######################
#       Settings     #
######################
# set rm_temp = 1 to delete temp file
# set block_size as the number of data to be averaged
# set droped as the number of data to be droped
rm_temp_file=1
block_size=500
droped=0


###################################
#     Calculate Block Average     #
###################################
filename=$1
grep -IRPo  "(?<=DVDL=)\s+\-?\d+\.\d+"   $filename  | sed "s/ //g"  > dvdl0_$filename
totl=`wc -l dvdl0_$filename | cut -d ' ' -f1`; totl=`echo $totl - $droped | bc `
tail -$totl dvdl0_$filename > dvdl_$filename
nblock=`echo $totl / $block_size | bc `
nrest=`echo $totl % $block_size | bc `
if [ $nrest -gt 0 ] ; then
    nblock=`echo $nblock+1 | bc` 
fi

echo totl $totl
echo nblock $nblock
echo nrest $nrest

blkcnt=1  # block counter
counter=1  # in block counter
avg_dvdl=0.0 # average

while read line
do
    dvdl=$line
    #echo dvdl $dvdl
    avg_dvdl=`echo $avg_dvdl + $dvdl | bc -l`
    #echo $avg_dvdl
    if [ $counter -lt $block_size ]; then
        counter=`expr $counter + 1` 
        #echo counter $counter
    else
        #echo $dvdl
        avg_dvdl=`echo "scale=8; $avg_dvdl / $block_size" | bc -l ` 
        echo $avg_dvdl
        echo "$blkcnt "  $avg_dvdl >> block_average_$filename
        counter=1
        blkcnt=`expr $blkcnt + 1`
        avg_dvdl=0.0
    fi

    if [ $blkcnt -eq $nblock ]; then 
        if [ $counter -eq $nrest ] ; then
            echo $avg_dvdl
            avg_dvdl=`echo "scale=8; $avg_dvdl / $nrest" | bc -l `
            echo "$blkcnt "  $avg_dvdl average with  $nrest, not $block_size>> block_average_$filename
        fi
    fi
done < dvdl_$filename



###################################
#     Calculate MSE               #
###################################
awk '{print $2}'  block_average_$filename > block_average2_$filename
avg=0.0
avg2=0.0
while read line
do
    avg=`echo $avg + $line | bc -l`
    avg2=`echo $avg2 + $line*$line | bc -l`
done < block_average2_$filename
avg=`echo $avg/$nblock | bc -l`
avg2=`echo $avg2/$nblock | bc -l`
mse=`echo "scale=8; sqrt($avg2 - $avg*$avg)" | bc -l `
echo Average $avg
echo MSE $mse 
echo Average $avg >> block_average_$filename
echo MSE $mse     >> block_average_$filename



######################
#     Cleaning       #
######################
if [ $rm_temp_file -eq 1 ] ; then 
    rm -fr dvdl*_$filename
    rm -fr block_average2_$filename
fi

echo Done. Block averages are written in: block_average_$filename


