#!/bin/bash
#
# Find out free nodes on phoenix
# Created: 2015/08/03 Haiyun Jin
#

arg=$1

if [ "$arg" == "-h" ] ; then
    cat << EOF
Usage:"
  qhost [-a] [-h]"
  -a : show opportunity nodes as well"
  -h : show this help."

EOF
    exit 1;
fi

cui12="compute-1-30 compute-1-31 compute-1-32 compute-1-33 compute-1-34 compute-1-35 "


#downlist=""

function proceed {

#downlist="$downlist `pbsnodes -l down $list | awk '{print $1}'`"
list=`pbsnodes -l free $list | awk '{print $1}'`

if [ "$list" == "" ] ; then
    #echo  "Oops! No free" ${np}-core machine with mem $mem.
       #list=$chem8       ; mem=23  ; np=8  ; proceed ;
    true
else

pbsnodes  -x $list |sed  -r 's$</Node><Node>$&\n$g' > /dev/shm/qhosttemp_$LOGNAME
while read -r line
do      
#    idown=`echo $line |  grep -c "offline\|down"`
#    if [ $idown == 0 ] ; then

        # if jobs is empty, then it is full to be used
        jobs=`echo $line | grep -IRPo  "(?<=<jobs>).+(?=</jobs>)" `    # get jobs information
        if [ "$jobs" == "" ] ; then
            name=`echo $line | grep -IRPo  "(?<=<name>).+(?=</name>)"`     # get node name
            #printf  "%-18s%4s%16s%15s\n" $name $np $mem 
            freenode=$((np +freenode))
        else  
            freenp=`echo $np - $(echo $jobs | sed 's/, /\n/g' | wc -l) | bc -l `
            if [ $freenp != 0 ] ; then
                name=`echo $line | grep -IRPo  "(?<=<name>).+(?=</name>)"`     # get node name
                #printf  "%-18s%4s%16s%15s\n" $name $freenp $mem # $properties
            freenode=$((freenp +freenode))
            fi
        fi
#    else
#        name=`echo $line | grep -IRPo  "(?<=<name>).+(?=</name>)"`
#        downlist="$downlist $name"
#    fi


done <  /dev/shm/qhosttemp_$LOGNAME
#rm -f  /dev/shm/qhosttemp_$LOGNAME


fi
}


title='  Cui Machine  ' ; #write_title ;
    list=$cui12       ; mem=31  ; np=12 ; proceed ;

    echo ${freenode}


#echo "The following nodes are down:"
#echo $downlist
#echo
#for x in $downlist
#do
#    echo $x
#done



