#! /bin/bash

if [ $# = 2 ] ; then  
  n1=$1; n2=$2
  temp=`echo sqrt\($n1*$n1+$n2*$n2\) |bc -l `
  echo ; echo $temp ; echo

elif [ $# = 3 ] ; then
  n1=$1; n2=$2; n3=$3
  temp=`echo sqrt\($n1*$n1+$n2*$n2+$n3*$n3\) |bc -l `
  echo ; echo $temp ; echo

elif [ $# = 6 ]; then
  n1=$1; n2=$2; n3=$3; n4=$4; n5=$5; n6=$6;
  #temp=`echo sqrt\(\($n1+\(-1\)*$n4\)*\($n1-$n4\)+\($n2-$n5\)*\($n2-$n5\)+\($n3-$n6\)*\($n3-$6\)\) |bc -l `
  temp=`echo sqrt\(\($n1+\(-1\)*$n4\)^2+\($n2+\(-1\)*$n5\)^2+\($n3+\(-1\)*$n6\)^2\) |bc -l `
  echo ; echo $temp ; echo

else
    echo Need 2/3/6  coordinates...
fi

