#!/bin/bash

if [ $# == 0 ];  then
    joblist=`qstat -u $LOGNAME | cut -d "." -f1 | grep -e [0-9]`
else
    while [ "$1" != "" ]; do
        joblist="$joblist $1"
        shift;
    done
fi

for x in $joblist; do
    node=`qstat -f $x | grep -IRPo  "(?<=exec_host = )[a-z]+\-\d+\-\d+" `
    echo $x " :" $node
done

